### ISSUE TITLE
Matplot autocorrelation 

### ISSUE THREAD

**Issue by piantado** [pymc-devs/pymc3#107]
I get crashes on pymc.Matplot.plot for the autocorrelation plot sometimes, especially with small sample sizes. This kills plotting of all variables. A quick fix would be to wrap line 399 of Matplot.py, which calls autocorrelation, with a try/except, and warn on an error.

**Comment by fonnesbeck** [comment]
Thanks for the report. Fix pushed in bb76442a09a52400e2a3b5b17e8a38c09ee8a144. Please test.

**Comment by piantado** [comment]
Sorry, I still get this error:  

 File "model8.py", line 203, in <module>
    pymc.Matplot.plot(S, path=args['out']+"/plots/")
  File "/usr/local/lib/python2.6/dist-packages/pymc/Matplot.py", line 312, in wrapper
    f(data, name, _args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/pymc/Matplot.py", line 398, in plot
    autocorrelation(data, name, rows=rows_2, columns=2, num=num+3_(num-1)+2, last=last, fontmap=fontmap)
  File "/usr/local/lib/python2.6/dist-packages/pymc/Matplot.py", line 347, in wrapper
    f(pymc_obj, _args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/pymc/Matplot.py", line 704, in autocorrelation
    acorr(data, detrend=mlab.detrend_mean, maxlags=maxlags)
  File "/usr/lib/pymodules/python2.6/matplotlib/pyplot.py", line 1628, in acorr
    ret = ax.acorr(x, *_kwargs)
  File "/usr/lib/pymodules/python2.6/matplotlib/axes.py", line 3738, in acorr
    return self.xcorr(x, x, *_kwargs)
  File "/usr/lib/pymodules/python2.6/matplotlib/axes.py", line 3805, in xcorr
    if normed: c/= np.sqrt(np.dot(x,x) \* np.dot(y,y))
FloatingPointError: invalid value encountered in true_divide

**Comment by fonnesbeck** [comment]
Ok, I think I nabbed this in de8f9ac2bce60cee23a759cd9272ef6bb82aa851. Please test.

**Comment by piantado** [comment]
Great, thanks!!
