### ISSUE TITLE
AttributeError: 'MCMC' object has no attribute '_stop_tuning_after'

### ISSUE THREAD

**Issue by roban** [pymc-devs/pymc3#111]
A demonstration of this error is below. I think perhaps line 348 of MCMC.py should be

```
    if self._burn_till_tuned:
```

instead of

```
    if not self._tune_throughout:
```

Error example:

```
>>> import pymc
>>> n = pymc.Normal('n', 1.0, 1.0)
>>> m = pymc.MCMC([n])
>>> m.sample(10, burn=1, tune_interval=5, tune_throughout=False)
>>>                0%                  ] 
>>> m.sample(10, burn=5, tune_interval=5, tune_throughout=False)
------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymc/MCMC.py", line 250, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/usr/local/lib/python2.7/dist-packages/pymc/Model.py", line 243, in sample
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/pymc/MCMC.py", line 269, in _loop
    self.tune()
  File "/usr/local/lib/python2.7/dist-packages/pymc/MCMC.py", line 358, in tune
    if self._tuned_count ==  self._stop_tuning_after:
AttributeError: 'MCMC' object has no attribute '_stop_tuning_after'
```

**Comment by fonnesbeck** [comment]
Thanks for reporting. Your fix isn't quite right, as we need to account for instances where we are not burning until tuned, but also not tuning throughout. I pushed the fix in 642cb07e3cd6685d84c50f91e9492e4fba2ce137

**Comment by roban** [comment]
Hmm, 642cb07 doesn't fix it for me. Running the same test as above:

```
>>> import pymc
>>> n = pymc.Normal('n', 1.0, 1.0)
>>> m = pymc.MCMC([n])
>>> m.sample(10, burn=5, tune_interval=5, tune_throughout=False)
```

still gets me the AttributeError.

I could be reading the code wrong, but I think that block (lines 348-360) is only needed when burn_till_tuned is set. If burn_till_tuned is False, and tune_throughout is also False, tuning is stopped instead by line 284 in the _loop function. 

It _is_ a little confusing that tuning is terminated in different functions depending on the parameters to sample, so maybe this should be consolidated. But I think my original solution is valid.

**Comment by fonnesbeck** [comment]
OK, fixed in e421f648cf1019f3cae456bd6da917c5185126e3
